---
name: گزارش ایراد
description: گزارش مشکلی که هنگام استفاده از هلپ‌دسک دیده‌اید
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        به بخش ثبت مسئلهٔ هلپ‌دسک خوش آمدید. پیش از ثبت، این موارد را بخوانید:

        ۱. از این بخش فقط برای گزارش ایراد یا پیشنهاد قابلیت و بهبود هلپ‌دسک استفاده کنید.
            - برای پرسش و پشتیبانی عمومی، [مستندات](https://docs.frappe.io/helpdesk) یا [انجمن](https://discuss.frappe.io) را ببینید.
            - برای اصلاح مستندات، پیشنهاد تغییر را مستقیماً در [وب‌سایت مستندات](https://docs.frappe.io/helpdesk) ثبت کنید.
        ۲. همهٔ اطلاعات لازم را بنویسید تا بازتولید مشکل برای نگه‌دارندگان آسان‌تر شود.
        ۳. اگر علت احتمالی را می‌دانید، توضیح دهید؛ حتی می‌توانید Pull Request بفرستید 😉

  - type: textarea
    id: bug-info
    attributes:
      label: شرح ایراد
      description: بگویید انتظار داشتید چه اتفاقی بیفتد. در صورت نیاز برای توضیح مشکل تصویر اضافه کنید.
      placeholder: لطفاً جزئیات لازم را بنویسید.
    validations:
      required: true

  - type: textarea
    id: exact-version
    attributes:
      label: نسخه
      description: شمارهٔ دقیق نسخهٔ Frappe و Helpdesk را بنویسید.
      placeholder: |
        نسخهٔ Frappe:
        نسخهٔ Helpdesk:
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: روش نصب
      options:
        - docker
        - easy-install
        - manual install
        - FrappeCloud
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: خروجی مرتبط لاگ، Stack trace یا متن کامل خطا
      description: خروجی مرتبط را کپی کنید؛ متن به‌صورت خودکار قالب‌بندی می‌شود.
      render: shell
