---
name: پیشنهاد قابلیت
description: پیشنهاد ایده‌ای برای بهبود هلپ‌دسک
labels: ["feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        به بخش ثبت پیشنهاد هلپ‌دسک خوش آمدید. پیش از ثبت، این موارد را بخوانید:

        ۱. از این بخش فقط برای گزارش ایراد یا پیشنهاد قابلیت و بهبود هلپ‌دسک استفاده کنید.
            - برای پرسش و پشتیبانی عمومی، [مستندات](https://docs.frappe.io/helpdesk) یا [انجمن](https://discuss.frappe.io) را ببینید.
        ۲. پیش از ثبت، جست‌وجو کنید؛ پیشنهادهای تکراری بسته می‌شوند و به گفت‌وگوی اصلی ارجاع داده خواهند شد.
        ۳. مسئله و راهکار پیشنهادی را تا جای ممکن دقیق توضیح دهید.


        تعداد پیشنهادها زیاد است و امکان پیاده‌سازی همهٔ آن‌ها وجود ندارد. اولویت توسعه براساس هدف‌های محصول و سازمان تعیین می‌شود؛ بااین‌حال پیشنهادها به تصمیم‌گیری‌های آینده کمک می‌کنند.

        اگر برای قابلیتی زمان‌بندی فوری دارید، برای توسعهٔ سفارشی می‌توانید از این مسیرها کمک بگیرید:
        ۱. همکاران تأییدشدهٔ Frappe: https://frappe.io/partners
        ۲. انجمن توسعه‌دهندگان Frappe: https://discuss.frappe.io/c/developers/5
        ۳. گروه تلگرام توسعهٔ Frappe Helpdesk: https://t.me/+eBnEZm7urwEwYTc1

  - type: textarea
    id: problem-info
    attributes:
      label: آیا این پیشنهاد به مشکلی مربوط است؟ آن را شرح دهید.
      description: مشکل را روشن و کوتاه توضیح دهید؛ مثلاً «هر بار که ... کلافه می‌شوم».
      placeholder: لطفاً جزئیات لازم را بنویسید.

  - type: textarea
    id: solution-info
    attributes:
      label: راهکار پیشنهادی
      description: توضیح دهید دوست دارید چه اتفاقی بیفتد.

  - type: textarea
    id: alternatives-info
    attributes:
      label: راهکارهای جایگزینی که بررسی کرده‌اید
      description: گزینه‌های دیگری را که در نظر گرفته‌اید توضیح دهید.

  - type: textarea
    id: additional-info
    attributes:
      label: اطلاعات تکمیلی
      description: توضیحات یا تصویرهای دیگری را که به درک پیشنهاد کمک می‌کنند اضافه کنید.
